### ISSUE TITLE
Disable automatic URL Highlighting in Highlight-Scroll bar

### ISSUE THREAD

**Issue by JanSHUP** [sieukrem/jn-npp-plugin#103]
Hey, 

I really appreciate your highlighting feature in NPP+ scroll bar.

However in my current setup not only the marked elements but also all hyperlinks in .txt files are marked permanently.
Marked elements in green, hyperlinks permanent in black. 

Since the highlighting indicators are quite small I can't differentiate at a glance if its a hyperlink or a highlight.

- For me it would be best to disable the automatic hyperlink-highlighting but I can't find any settings.
- If this is hard to implement it would be nice to increase the indicator size, especially the color-region.

I never did NPP Plugin development and have no idea where to change theses settings. Could you give me hint?

thanks and best regards, Jan

**Comment by sieukrem** [comment]
My setup does not highlight urls, hence I can not try out the solutions. 
I would ask you to try it out by your self. 
1. Please open the "Smart Highlighter" -> Settings 
![img](http://i.imgur.com/ib3o5hi.png)
2. Uncheck check boxes one by one until the indicator for the URL disappears

If it did not helped, then we need to investigate your setup further

**Comment by JanSHUP** [comment]
Thanks a lot, 
it is indicator #9 on my system.
I found that the auto highlighting only is enabled for URLs starting with "HTTP" or "HTTPS"
e.g. "https://www.example.com"
Sometimes the link itself is only underlined in the beginning but if I scroll through the document or as soon as I open the link via double click also the highlighting in the highlighting bar is permanent.
Nevertheless unchecking Box #9 solves this issue.

Thanks a lot, Jan
