### ISSUE TITLE
Wrong menu position since Notepad++ v8.4.3

### ISSUE THREAD

**Issue by text-dev** [sieukrem/jn-npp-plugin#112]
In Notepad++ v8.4.3 there were added new shortcuts of document management on the right side of menu (2 more shortcuts “plus” (new file) and “arrow”). The menus of jn-npp-plugin are now between the "plus" and the "arrow" item on the right side, but they should be at the old position between the "window" and "?" item.

In the screenshot Notepad++ v8.4.2 is at the top in the background.

![grafik](https://user-images.githubusercontent.com/38277306/183593512-a785e7f6-8d4e-4d3e-9ec2-4ee1452e2d53.png)

 - OS: Win10
 - OS Arch: x64
 - Notepad++ Version: v8.4.4
 - Notepad+ Arch: x64
 - jN Version: 2.2.185.7

**Comment by sieukrem** [comment]
@text-dev  thanks for the issue reporting!
Can you please check the fix https://ci.appveyor.com/project/sieukrem/jn-npp-plugin/builds/44603126/job/ioju8h7qq40n0u3q/artifacts !

**Comment by text-dev** [comment]
Thank you for the fix. It works.

I would need this for the 32-bit version as well.

**Comment by sieukrem** [comment]
The new version can be downloaded from [release page](../releases/tag/2.2.185.8). 
The integration into npp plugin list is pending.
