### ISSUE TITLE
Win32 API call problem

### ISSUE THREAD

**Issue by blackcatt** [sieukrem/jn-npp-plugin#113]
Got problem with win32 api call at fresh Windows 10x64 (21H2), newest npp8.4.4 (x64), newest JN-NPP, run@administrator, 
```
require("lib/Window.js");
require("lib/scintilla.js");
require("lib/User32.dll.js");

var sci = new Scintilla(currentView.handle);
rw = sci.Call("SCI_GETLEXER"); 
alert(rw); // fire 0

var rv = User32.MessageBoxW(Editor.handle,"Вопрос вопроса","Привет",1); // nothing fire
alert(rv); // fire 0
```
This code fire two alerts with zero inside. I was expecting another)

**Comment by sieukrem** [comment]
Win API calls are supported for x86 npp and jn. I started the implementation for x64 but did not finish.

**Comment by blackcatt** [comment]
Thank you, on x86 it works. 
And what about **GlobalListener.removeListener** ? Looks like this is also not implemented?

**Comment by sieukrem** [comment]
> GlobalListener.removeListener ? Looks like this is also not implemented?

You are right, it is missing! If you need it and can develop it in start.js, I would appreciate a pool request.

**Comment by sieukrem** [comment]
Closing this issue, because clarified
