### ISSUE TITLE
Error attempting to use Object.assign

### ISSUE THREAD

**Issue by technificentConsulting** [sieukrem/jn-npp-plugin#114]
An example that produces the following error.  "Object doesn't support this property or Method local_67178280.js. "
What am I doing wrong?  Is this a limitation of the plugin?  Any suggestions are appreciated.

After typing the following line I hit Run -> Current View and the error above is produced.
`var test = Object.assign({}, {"keyname": {}});`

**Comment by KOLANICH** [comment]
IE 6 has no modern ECMAScript

**Comment by technificentConsulting** [comment]
@KOLANICH oh ok...that makes sense.  Thanks!
