### ISSUE TITLE
Make the right minimap bigger in high dpi monitors

### ISSUE THREAD

**Issue by onolox** [sieukrem/jn-npp-plugin#116]
Hi, the collumn on the right that show the  "minimap" of the highlighted words needs to be bigger in high dpi monitors.

In this kind of monitor it is almost invisible.

![image](https://user-images.githubusercontent.com/11450681/227221835-f9099cfe-b7b4-495e-bba1-66b4131ccae8.png)

**Comment by sieukrem** [comment]
@onolox thanks for reporting the issue!

Please check on your display following fix in dependence on your environment [x86](https://ci.appveyor.com/project/sieukrem/jn-npp-plugin/builds/46587520/job/bapfc0b5faad16a8/artifacts), [x64](https://ci.appveyor.com/project/sieukrem/jn-npp-plugin/builds/46587520/job/moidtbdgag7t3sfl/artifacts)

**Comment by onolox** [comment]
In regards of width is good, but maybe it can be more tick, have more height.

**Comment by onolox** [comment]
I tried the x64 jn.dll in my new n++ v8.5 and the plugin don't load anymore.

**Comment by onolox** [comment]
yes n++ x64

**Comment by sieukrem** [comment]
Please check the thickness of indicators
[x64](https://ci.appveyor.com/project/sieukrem/jn-npp-plugin/build/job/epfi8qg29ostm803/artifacts)
[x86](https://ci.appveyor.com/project/sieukrem/jn-npp-plugin/build/job/u0c8alaeyk6gv1mx/artifacts)

**Comment by onolox** [comment]
now it's better to see! 
Thanks!
