### ISSUE TITLE
Spurious markers near the vertical scroll bars for smart highlighting

### ISSUE THREAD

**Issue by mahaju** [sieukrem/jn-npp-plugin#123]
**Describe the bug**
When opening a large document vertical scrollbars show locations of highlighted words, even though I have not highlighted anything yet

**To Reproduce**
1. Open a large document
2. Do not highlight anything, just use the vertical scrollbar to scroll through the document
3. Position of highlighted words start appearing next to the vertical scroll bars, even though I have not highlighted anything
4. Once I highlight a word, positions of the highlighted words start appearing along side the spurious markers previously explained; unhighlighting the word makes its markers disappear, but the spurious markers remain

This happens randomly for me and I don't have an exact way to reproduce this, but whenever it does happen the steps mentioned above will produce it. I also usually have a large number of tabs open, although I am not sure if this is relevant. 

**Expected behavior**
The markers next to the vertical scrollbar should only appear when I highlight words, and should disappear when I unhighlight them.

**Screenshots**
This is when I just open this large document.
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/23d083c6-8db4-4cea-9271-9c501d28d959)

I do not highlight any word, but just scroll down clicking and dragging the scroll bar
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/fb48c529-41f5-412b-81fe-ba74b1d6469a)

I highlight a frequently occurring word
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/0f667185-b8bc-40dd-a2bb-919d970a426e)

I unhighlight the frequently occuring word
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/f5290309-ea30-4d51-800b-2aecbc9867b1)

Is this a bug or is there a setting I need to change? I only use the jN plugin for the smart highlighting feature so I don't know any details about the plugin settings. I have kept everything at their default.

**Environment**
 - OS: Windows 10 Pro 22H2 build 19045.3324
 - OS Arch: x64
 - Notepad++ Version v8.2.1 (64-bit)
 - Notepad+ Arch: x64
 - jN Version : 2.2.185.6
 
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/3ecbde4c-3206-4b20-83c5-96ac9371569e)

![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/82636fb2-8742-4029-8fbb-0e340a830683)

**Comment by sieukrem** [comment]
It seems to be a bug. Can you please check with latest [release](https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.9)

**Comment by mahaju** [comment]
I updated with the latest release [renamed the old jN folder to jN.2.2.185.6, copied everything in jN_2.2.185.9_x64.zip to a new jN folder inside "C:\Program Files\Notepad++\plugins"]

The problem is still happening
The markers seem to be thicker this time
Again, this happens randomly and it's happening in some files and not happening in others (but in the files that it does happen, it always happens)
For example, here is a .kt file with no word highlighted:
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/6f3b1dcd-9124-4d51-ae25-16b1f40bc489)
I have another .kt file open that behaves normally. I don't know what is the difference between the two .kt files.

I will revert back to the older jN version for now, because I prefer the thinner markers. Let me know if you would like me to test something else.

**Comment by mahaju** [comment]
I was looking at the "smart highlighter" settings
![image](https://github.com/sieukrem/jn-npp-plugin/assets/1299251/fbc0b7d6-c171-44cd-ab4b-414d245f534b)
and I noticed that if I uncheck all the boxes, all smart highlighting markers go away, both legitimate and spurious. Could changing anything here get rid of the spurious markers? Do you have any documents that explain what the 32 options are?

Seem this is something related to the "SmartHighlighter.js" file in C:\Program Files\Notepad++\plugins\jN\jN\includes, but I don't know any javascript. Some document explaining what the 32 options are (all I figure out is it seems to be some kind of bit mask) would be helpful, if these settings are relevant to getting rid of the spurious markers.

**Comment by naaitsab** [comment]
Looks to be related to specific document content. Tested some random files in the same session.
Works fine: log, xml, txt, js, psc and new unsaved file (new 1) 
Issue: toml
When I copy the text content from the toml file to one of the files that works as normal it shows the exact same issue as the toml file and what the OP references to. When I delete the text again on all open documents that have it in, it reverts to normal. If I leave the text in one of the documents it shows the black bars at random when selecting the file in the tab of N++

The toml file content for reference:
`[PriorityMod]
enabled = true

## Priorities
# No Change     = -1
# Idle          = 0
# Below Normal  = 1
# Normal        = 2
# Above Normal  = 3
# High          = 4
# Realtime      = 5     (Run as Administrator is required) (Not Recommended)
# Check Microsoft official document for the details:
# https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass#parameters
# It's recommended to keep this at 4
priority = 4

## Affinity
# Process Affinity (0 = no change)
# Check Microsoft official document for the details:
# https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups

# To set the value. You may need CPU Affinity Mask Calculator:
# https://bitsum.com/tools/cpu-affinity-calculator/
# Read Edenfall's comment for more information:
# https://www.nexusmods.com/skyrimspecialedition/mods/50129/?tab=posts
affinity = 0x000000000000FFF5

## Dynamic Priority
# For people who have bAlwaysActive=true
# Priority and affinity will be set to the value below when lost focus.
# Regain focus or not responding will be set back to [PriorityMod] section.
[DynamicPriority]
enabled = false
idle_priority = 1
idle_affinity = 0

## ENBHost Priority
# Only for 32bit games with ENB.
# Related code won't be included at Compile-Time in Fallrim Priority 64bit.
# So you don't need to disable it when you playing 64bit games like Skyrim SE/AE or Fallout 4.
[EnbHost]
enabled = true
priority = 4
affinity = 0
`

**Comment by sieukrem** [comment]
I could reproduce the issue! 
1. URLs in documents are using indicator 9 and are black, these are spurious markers, which appear als when nothing is selected. Just unselect the indicator 9 in Smart Highlighter Settings
2. There is a bug in jN which was uncovered through behavior change somewhen after N++ version v7.xx. Switching from huge documents to smaller lead to left overs in the indicator panel. I will push a fix soon.

**Comment by sieukrem** [comment]
Please check the [latest release](https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.10)!

**Comment by mahaju** [comment]
Here are some of my findings:
1. URLs are indeed the spurious markers. Unselecting indicator 9 removes them.
2. Using latest release, I get the same effect I mentioned previously at https://github.com/sieukrem/jn-npp-plugin/issues/123#issuecomment-1683490967
that is, spurious markers still appear, but all markers are now thicker

Since I prefer thinner markers, for now the best solution for me is to just uncheck indicator 9

Would you mind sharing any documents explaining what the different indicators are and what they do?
