### ISSUE TITLE
Smart highlighter not working correct

### ISSUE THREAD

**Issue by akniesel** [sieukrem/jn-npp-plugin#125]
**Describe the bug**
When I highlight a word with double click, only at the current scroll bar position the lines are highlighted:
![1](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/04c2f3d8-16ec-4ab0-b9ff-bc17e0059b25)

Only if I scroll the scroll bar from top to bottom, the positions are displayed correctly:
![2](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/98f00d44-7b4a-442c-8835-00ab5797e096)

**Environment**
 - OS: Win10 64
 - Notepad++ Version 8.6.4
 - jN Version 2.2.185.10

**Comment by sieukrem** [comment]
I have observed this behavior in the past, but can not reproduce now. I believe it was a setting of N++ I changed. 

Can you please share screenshots of Preferences:
* General
* Editing
* Highlighting 
* Searching
* MISC.

Did you have another N++ version which behaves differently?

**Comment by akniesel** [comment]
I tried also older Versions of the plugin as well as NPP, but no success.
![NPP-1-General](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/a11fafd1-b984-4bd5-baf1-fabff4a91857)
![NPP-2-Edit](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/21b813dd-bd16-4f0f-843e-9dbb2c5a77fe)
![NPP-3-Highlighting](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/e3d15e1e-3b69-4e71-972a-b087dbde2409)
![NPP-4-Searching](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/595e7e0f-198d-435d-a50d-8c8f336c6248)
![NPP-5-Misc](https://github.com/sieukrem/jn-npp-plugin/assets/161830762/5ffea2ae-85b2-4e2f-aa11-dab3190c1078)

**Comment by gepparta** [comment]
I have the same issue like @akniesel 
Workaround for me is to use the plugin 
![image](https://github.com/sieukrem/jn-npp-plugin/assets/3863263/d6d0bf7c-8bd1-4af7-b9b1-178c0e35b657)

**Comment by sieukrem** [comment]
@akniesel if you would read through #82, would you mind to have same observations?

**Comment by sieukrem** [comment]
> @akniesel if you would read through #82, would you mind to have same observations?

I could reproduce your observation with 8.6.4. It is some kind of optimization on either Scintilla or N++, some of them notifies plugin about update on the styling of only currently visible text. If you switch between tabs, jn-npp-plugin forces update for styling of the entire text.

I will check what are our options.

**Comment by akniesel** [comment]
Any updates so far?

**Comment by 011V32** [comment]
I have the same issue. Update would be great. Thx

**Comment by sieukrem** [comment]
I would appreciate if someone could test [x64](https://github.com/sieukrem/jn-npp-plugin/actions/runs/11222650458/artifacts/2025830216) and [x86](https://github.com/sieukrem/jn-npp-plugin/actions/runs/11222650458/artifacts/2025832904) versions!

**Comment by akniesel** [comment]
It seems to work!

Great job.

**Comment by 011V32** [comment]
x64 works for me too 👍 
thx

**Comment by sieukrem** [comment]
@akniesel, @011V32  thanks for testing!
