### ISSUE TITLE
string.split(separator) removes consenquent separator characters

### ISSUE THREAD

**Issue by luboss** [sieukrem/jn-npp-plugin#126]
**Describe the bug**
split() method of string object consumes consequent characters while not adding elements to the final array which causes removing empty lines in case you want to split multi-line string.

**To Reproduce**
Below code returns 3 lines instead of 6: 
`"first line\n\nthird line (after 1 empty line)\n\n\nend".split(/\r?\n|\r|\n/g).join('\r\n')`

Running the same code in browser returns  correctly 6 with preserved empty lines.

**Expected behavior**
split() correctly creates empty elements in case for consequent separator characters in a row

**Environment**
 - OS: Win11
 - OS Arch: x64
 - Notepad++ Version: 8.6.5
 - Notepad+ Arch: x64
 - jN Version 2.2.185.9

**Additional context**
In general, this javascript implementation is either outdated or not fully covered.

**Comment by sieukrem** [comment]
Yes, you are right. The javascript engine used here is from early ages of widely used VBA implementations.

We cannot change this behavior.

**Comment by luboss** [comment]
Thanks for explanation. I've rewritten the function myself.
Still this plugin rocks, it saves me some time and it's much more convenient than doing copy & paste into and out from a web app.
