### ISSUE TITLE
SmartHighlight.js highlights misspelled words

### ISSUE THREAD

**Issue by mdiokwe** [sieukrem/jn-npp-plugin#21]
I noticed that if you have DSPellCheck plugin running to highlight mispelled words, SmartHighlight will show all these on the side. I was wondering if this was intended, if so, is there a way to disable it?
It makes it hard to see the actual highlighting you want, when working with large files that have a lot of mis-spelled words in the comments.

![image](https://cloud.githubusercontent.com/assets/13986787/9503508/5da7483e-4c05-11e5-9091-0a113d570dd1.png)

Love the feature. Nice work.

**Comment by danielo515** [comment]
Oh, so that is the reason of the red lights on the right! it is disturbing for me also.

**Comment by sieukrem** [comment]
Fixed with release 2.1.181
