### ISSUE TITLE
Scintilla is not working

### ISSUE THREAD

**Issue by danielo515** [sieukrem/jn-npp-plugin#22]
I just copy pasted the example that is on the wiki, hit F5 and got the following error:

---------------------------
Microsoft JScript runtime error
---------------------------
Exception thrown and not caught
line: 176, pos: 10
---------------------------
OK   
---------------------------

I want to use scintilla to style text. If there is an easier way, I would love to know about it.

**Comment by sieukrem** [comment]
What example did you use?

**Comment by eight04** [comment]
I can get this error with following code
```
require("lib/Scintilla")
```
Try to print the error
```
try {
	require("lib/Scintilla")
} catch (err) {
	alert(err);
}
```

```
File does not exist: lib/User32.dll.js
```

It is a bug related to `require` system.

The require function will look file from:
1. Current working directory, which is `C:\Program Files (x86)\Notepad++`.
2. `require.currentDir` which is `C:\Program Files (x86)\Notepad++\plugins\jN` at first. After requiring Scintilla, it becomes `C:\Program Files (x86)\Notepad++\plugins\jN\lib`

So it just fails to require lib/User32.dll.js (`C:\Program Files (x86)\Notepad++\lib/User32.dll.js` and `C:\Program Files (x86)\Notepad++\plugin\jN\lib\lib/User32.dll.js`)

**Comment by sieukrem** [comment]
Try following code

`require("lib/scintilla.js")`

**Comment by eight04** [comment]
Still the same error
![image](https://i.imgur.com/Qb4zEVz.png)

**Comment by sieukrem** [comment]
Please verify if recently updated files user32.dll.js, kernel32.dll.js, scintilla.js solve your problem

**Comment by eight04** [comment]
Confirmed the fix with latest commit! Thank you very much :smile:
