### ISSUE TITLE
Recommendations for getting user input?

### ISSUE THREAD

**Issue by fspafford** [sieukrem/jn-npp-plugin#23]
What is the recommended way to get user input?

I would like to give a prompt string and get user input.

Thanks again for creating the plugin.

Frank

**Comment by thorn0** [comment]
You can use [this approach](https://github.com/thorn0/jnscripts/blob/33d3cdf34b88a099b32b2ec69ea424048b32647f/includes/!inpubox.js).

**Comment by sieukrem** [comment]
Did you try Dialog.prompt()?

E.g.
Dialog.prompt("XPath", "default value", function(value){ // called on <enter>
	return alert(value);
})

You can create you own prompt dialog using HTML. Take a look into \includes\Dialog.js where Dialog.prompt is defined.
