### ISSUE TITLE
wrong plugins folder 

### ISSUE THREAD

**Issue by seantw** [sieukrem/jn-npp-plugin#24]
for security some plugins directory is in %APPDATA%\Notepad++\plugins
not in C:\Program Files\Notepad++\plugins

so...
Editor.nppDir+"\\Plugins\\jN\\includes"
In some cases, wrong.

**Comment by sieukrem** [comment]
Hello Sean, please check if it works as you expect.

**Comment by seantw** [comment]
Everything is fine!
