### ISSUE TITLE
Several MODIFYATTEMPTRO fired in column mode

### ISSUE THREAD

**Issue by MiFoe** [sieukrem/jn-npp-plugin#25]
Hello,
I use Clearcase SCM which checkout a file on MODIFYATTEMPTRO. In column mode the event is fired for every line and I get the several checkout dialogs. Even in single line mode sometimes the event is fired twice. As workaround I changed the clearcase.js to:

	var PendingCheckouts = {};
	// Add handler to catch event if user tries to modify checked in file
	// and allow him to check out it
	GlobalListener.addListener({ MODIFYATTEMPTRO:function(v){
		var file = getFile();
		var version = null;
		
		try{
		version = helperCC.Version(file);
		}catch(e){}
      
		if (version == null || version.IsCheckedOut)// nothing to do from point of view of ClearCase
			return;
		if ( PendingCheckouts[file] )
			return;
		PendingCheckouts[file] = 1;
		shell.run("cleardlg /checkout \""+file+'\"',0,1);
		delete PendingCheckouts[file];
	}});

Is there a better way?

**Comment by sieukrem** [comment]
Hello,
because we don't use clearcase anymore, I cannot verify this issue exactly.

I use the same principle to checkout TFS files. My Notepad++ v6.5 fires this event also in column mode once.

You changed 
```javascript
//from
shell.run("cleardlg /checkout \""+file+'\"'); // creates popup and runs without waiting
//to 
shell.run("cleardlg /checkout \""+file+'\"',0,1); // wait 
```
I think that waiting could be enough without collecting PendingCheckouts to solve this issue

**Comment by MiFoe** [comment]
Hello,
you are right, waiting is enough.
