### ISSUE TITLE
view.lang is out of index

### ISSUE THREAD

**Issue by eight04** [sieukrem/jn-npp-plugin#26]
```
alert([Editor.langs.length, Editor.currentView.lang])
```
I get "51,58" with JavaScript, and "51,57" with JSON.

NPP v6.8.8
jN v2.1.181

**Comment by sieukrem** [comment]
Do you have any user defined language based document open in current view?

**Comment by eight04** [comment]
No. I can reproduce it with a newly opened file and select JavaScript language:
![](http://i.imgur.com/6FIMQiH.png)

If I select an User Defined Language I get:
![](http://i.imgur.com/KlXhONO.png)

**Comment by sieukrem** [comment]
When I built the first version there was only 51 supported languages. They are part of native public interface of Notepad++. The language ids are set of constants which can't be retrieved dynamically. Every time Notepad++ changes its public interface in this sense a new version of jN should be built. 

I will add new languages and share new binary in the next time
