### ISSUE TITLE
Dialog.js return error

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [sieukrem/jn-npp-plugin#27]
See context when using with Emment.:
https://github.com/eight04/jn-npp-emmet/issues/1

Edit: this error exist in previous version NppScripting and Dialog.js file too (if someone still uses). Problem is IE browser >9, so if anyone use something newer then should change line ~20:
`styles.styleSheet.cssText = this.cfg.css || '\nbody {overflow: auto;}\n';`
to
`styles.cssText = this.cfg.css || '\nbody {overflow: auto;}\n';`
or
`styles.textContent = this.cfg.css || '\nbody {overflow: auto;}\n';`

Edit: now Emmet use own wraper for dialog, but problem exist for included Zen Coding.

**Comment by sieukrem** [comment]
I can't reproduce this issue on Win7 IE 11 and Win10.

1. Did you installed Notepad++ or do you use CopyIn version
2. Is this issue reproducible when you use original installation of jN plugin
3. Did you modified IE embedding settings in windows registry for Notepad++
4. What is your Windows version
5. When you modify dialog.js is in the prompt dialog a scrollbar visible?

**Comment by ArkadiuszMichalski** [comment]
1. I use portable version (.zip from official NPP page)
2. Yep, I use original jN installation, but the same problem have in the past when using NppScripting.
3. I don't use IE so never change its options, only update frome IE9 > IE10 > IE11
4. Windows7 Ultimate Service Pack 1
5. No, scrollbar is hide and background was apply (style works fine), you can see this dialog in both script engine (after modification, as in my first post) http://postimg.org/image/qq9xypgph/

**Comment by sieukrem** [comment]
closed until I can reproduce this issue
