### ISSUE TITLE
Run jN menu commands via other plugins or add them to NPP context menu

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [sieukrem/jn-npp-plugin#28]
All scripts has own menu (in old style) so we can't add his options to NPP context menu or run them with other plugins. I test Zen Coding without any positive results:

- NPPExec, use `npp_menucommand Zen Coding|Wrap With Abbreviationd`, find this item but not invoke
- Python Script, use `notepad.runMenuCommand('Zen Coding', 'Wrap with  Abbreviation')`, like above, find this item but not invoke
- editing `contextMenu.xml` file without success 

The only solution what I found is write script for WSH (.js or .vbs) with send keys (shortcut for Zen Coding commands) and run this script with above tools. But it needs to define shortcut for any actions or other scripts (created via jN) which is inconvenient. This script can be add to Npp context menu and works.

Any advice how can I solve this in a more comfortable way?

**Comment by sieukrem** [comment]
Hello Arkadiusz,
I don't know any regular way to integrate new entries to existing context menu. It is like integration of plugin menu items, only declarative way is possible. It means either at compile time of plugin or contextMenu.xml before you start Notepad++. You understand, it is to few for flexible API. 
I was not enough and I built next dirty hack.
Did you see this [wiki page](https://github.com/sieukrem/jn-npp-plugin/wiki)?
Follow the article link under point 9. It describes the way how to create your own context menu, which conditionaly overrides the original one.
If you want to have context menu entries from original context menu, you can simulate them by interpreting the contextMenu.xml.

Happy scripting!

**Comment by ArkadiuszMichalski** [comment]
I saw this page and possibility to create own context menu, but I don't know how can I get commands from different jN scripts and put them to this context menu. Most of them (or maybe all) are anonymous and without refactoring code its impossible, or am I wrong? Would be nice if plugin will automaticaly collect all commands from all scripts and expose its somehow (via object), then it would be easy to build own context menu.

**Comment by sieukrem** [comment]
You are right! There is no regular way to collect all jN menu items. I don't think that it is good idea. Because not all of jN scripts are designed to be useful via context menu.
Indeed you can offer an API for jN scripts and than refactor them.

**Comment by ArkadiuszMichalski** [comment]
Hmm it would be easier if `cfg` for `addItem()` has additional boolean property for this so scripts autor can expose them for other scripts autor whenever they want. But in other site the same can be done without change anything, needs defined some standards js API and convince others to us it (if necessary).

**Comment by ArkadiuszMichalski** [comment]
@sieukrem
How can I reconstruct (get access) to command by their names (not ids), I mean both the command directly from the editor and the plugins. In `contextMenu.xml` file it's not a problem, but `Editor.runMenuCmd()` operate only on build-in menu command of Notepad++ exposed by number, so I can't rebuild original context menu. Is there any solution to solve this?

**Comment by sieukrem** [comment]
The only one way is to use the native Windows API ([GetMenuItemInfo](https://msdn.microsoft.com/de-de/library/windows/desktop/ms647980%28v=vs.85%29.aspx)) and Notepad++ ([NPPM_GETMENUHANDLE](http://docs.notepad-plus-plus.org/index.php/Messages_And_Notifications)). You can get the names of menu items and their Id's.

**Comment by ArkadiuszMichalski** [comment]
Any small example how do this? Looks like it's not so easy: https://github.com/eight04/jn-npp-emmet/issues/5#issuecomment-205477161
