### ISSUE TITLE
feature request: Run script at Notepad++ startup

### ISSUE THREAD

**Issue by fspafford** [sieukrem/jn-npp-plugin#29]
Is there a way to run a user script when Notepad++ starts?

If not, please consider adding this feature.

Thanks for creating the plugin!

**Comment by sieukrem** [comment]
All scripts in jn/includes directory are user scripts running at Notepad++ start.

**Comment by fspafford** [comment]
Thanks for the quick reply. You answered my question.
 

    On Tuesday, March 8, 2016 10:29 AM, Eugen Kremer <notifications@github.com> wrote:
 

 All scripts in jn/includes directory are user scripts running at Notepad++ start.—
