### ISSUE TITLE
Error using the Sass-Auto-Compile.js include

### ISSUE THREAD

**Issue by joelamos** [sieukrem/jn-npp-plugin#31]
I am attempting to use the [Sass-Auto-Compile.js](http://www.kuenzelit.de/blogContent/Sass-Auto-Compile.js) include. However, the script is unable to run, giving the error `The filename, directory name, or volume label syntax is incorrect.`

This seems to indicate that the problem is arising from the fact that there are spaces in the path to my Notepad++ installation.

**Comment by sieukrem** [comment]
Did you modify the 
`var pathToRubyBinDir = "C:/Programme Standard/Ruby193/bin/";`
in your copy of Sass-Auto-Compile.js?

**Comment by joelamos** [comment]
Yes, although I used an escaped trailing slash because without it I get a error from JScript telling me that I have an unterminated string constant.
