### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#32]
You are planing a x64 version?

**Comment by sieukrem** [comment]
I will prepare it in next few days

**Comment by lollita** [comment]
it's been a month, you have technical difficulties or time available?

**Comment by sieukrem** [comment]
As I wrote in other answer to an issue, it depends on new Visual Studio C++ compiler I need to build x64 version. This compiler crashes during compilation of win32 version. I saw that there are bug reports for that, so  I want wait a while.

An other issue is that x64 version of jN will not support native calls. I don't have a solution for this.

Time is also a thing, I'm building my new house

**Comment by lollita** [comment]
it is unfortunate that we will not have an soon and equivalent x64 plugin. 
what is the problem with the support native calls?

**Comment by sieukrem** [comment]
Native calls require some assembler magic. x64 uses registers instead of stack like x86.

**Comment by PeterBurner** [comment]
64Bit version would be great

**Comment by lollita** [comment]
It work except for "Library".
But is important for me.

**Comment by chcg** [comment]
@sieukrem Added the version https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185 to https://github.com/bruderstein/npp-plugins-x64/commit/9daec63d33035872399d0e83f1c71725e2d9aace, so it could be installed via PluginManager.
I hope that is ok for you.

**Comment by sieukrem** [comment]
Greate news, Thank you!

**Comment by BudiKusasi** [comment]
on now ‎Friday, ‎June ‎1, ‎2018, is the 64 bit version ready available ?

**Comment by sieukrem** [comment]
you can try one from latest release
https://github.com/sieukrem/jn-npp-plugin/releases

2018-06-01 11:59 GMT+02:00 BudiKusasi <notifications@github.com>:

**Comment by chcg** [comment]
What about using prerelease 2.2.185.2 for PluginManager? Or should I update to 2.2.185.1?

**Comment by chcg** [comment]
@sieukrem Fileversion of release 2.2.185.3 is still 2.2.185.0. This is relevant for the pluginmanager to identify the dll.

**Comment by chcg** [comment]
@sieukrem Thanks, update 32/64bit versions to 2.2.185.4 on the devlists.

**Comment by chcg** [comment]
@sieukrem Think this one could be closed.
