### ISSUE TITLE
launch chm and find a keyword

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#34]
Do it is possible to launch a chm file and find a keyword with internal [Scintilla](https://autohotkey.com/board/topic/9361-keyword-search-chm-from-cmdexe/) or [activex control](https://github.com/FallenPhoenix/akelpad-scripts-collection/blob/master/Instructor/ChmKeyword.js)?

I tryed this attempt:
`
require("User32.dll.js");
require("Kernel32.dll.js");
var bMaximize=true;
var bCatchEsc=false;

ChmKeyword("c:\\\\AutoIt.chm", "MsgBox");

function ChmKeyword(pFile, pKeyword)
{
	var _TSTR=0, _TSIZE=1;
	var hModule;
	var hWndHelpList=0;
	var hWndHelpChild;
	var hWndHelpFocus;
	var dwCurThreadID;
	var dwHelpThreadID;
	var hHook;
	var hMutex;

	//Load library manually to prevent hhctrl.ocx unload after HtmlHelp call
	var Kernel32 = new Library("Kernel32.dll");
	var User32 = new Library("User32.dll");
	if (!(hModule=Kernel32.GetModuleHandle("hhctrl.ocx")))
		hModule=Kernel32.GetModuleHandle("hhctrl.ocx");

	if (hModule)
	{
		var lpKeywordBuffer=User32.NativeLibrary.alloc(256 * _TSIZE);
		if (lpKeywordBuffer)
		{
			User32.NativeLibrary.writeByte(lpKeywordBuffer, pKeyword.substr(0, 255), _TSTR);

			var lpStructure=User32.NativeLibrary.alloc(_X64?56:32);//sizeof(HH_AKLINK)
			if (lpStructure)
			{
				//Fill structure
				User32.NativeLibrary.writeByte(lpStructure, _X64?56:32, 3 /*DT_DWORD*/);//HH_AKLINK.cbStruct
				User32.NativeLibrary.writeByte(lpStructure + (_X64?8:8), lpKeywordBuffer, 2 /*DT_QWORD*/);	//HH_AKLINK.pszKeywords
				User32.NativeLibrary.writeByte(lpStructure + (_X64?48:28), true, 3 /*DT_DWORD*/);					 //HH_AKLINK.fIndexOnFail

				hWndHelpDlg=hModule.HtmlHelp(User32.GetDesktopWindow(), pFile, 0xD /*HH_KEYWORD_LOOKUP*/, lpStructure);

				//Send VK_RETURN
				if (hWndHelpDlg)
				{
					dwCurThreadID=Kernel32.GetCurrentThreadId();
					dwHelpThreadID=User32.GetWindowThreadProcessId(hWndHelpDlg, 0);

					if (pKeyword)
					{
						if (User32.AttachThreadInput(dwCurThreadID, dwHelpThreadID, true))
						{
							hWndHelpFocus=User32.GetFocus();

							if (User32.GetWindowTextLength(hWndHelpFocus))
							{
								User32.SendMessageW(hWndHelpFocus, 0x0100 /*WM_KEYDOWN*/, 0x0D /*VK_RETURN*/, 0x011C001);
								User32.SendMessageW(hWndHelpFocus, 0x0101 /*WM_KEYUP*/, 0x0D /*VK_RETURN*/, 0xC11C001);
							}
							else User32.SetWindowText(hWndHelpFocus, lpKeywordBuffer);

							User32.AttachThreadInput(dwCurThreadID, dwHelpThreadID, false);
						}
					}

					if (bMaximize)
					{
						//Maximize CHM window
						User32.ShowWindow(hWndHelpDlg, 3);//SW_MAXIMIZE
					}
					/*
					if (bCatchEsc)
					{
						if (hMutex=Kernel32.CreateEvent(0, 0, 0, WScript.ScriptName))
						{
							//Allow WindowSubClass and ThreadHook only for single script
							if (oSys.GetLastError() != 183)//ERROR_ALREADY_EXISTS
							{
								//Catch WM_CLOSE
								if (AkelPad.WindowSubClass(hWndHelpDlg, SubClassCallback, 2)) //WM_DESTROY
								{
									//Catch VK_ESCAPE
									if (hHook=AkelPad.ThreadHook(3, HookCallback, dwHelpThreadID))//WH_GETMESSAGE
									{
										//Allow other scripts running
										AkelPad.ScriptNoMutex();

										//Message loop
										AkelPad.WindowGetMessage();

										//Wait while CHM window complitelly destroyed
										for (nTimeOut=5000; nTimeOut > 0 && oSys.Call("user32::IsWindow", hWndHelpDlg); nTimeOut-=100)
											WScript.Sleep(100);

										AkelPad.ThreadUnhook(hHook);
									}
									AkelPad.WindowUnsubClass(hWndHelpDlg);
								}
							}
							oSys.Call("kernel32::CloseHandle", hMutex);
						}
					}
				*/
				}
				User32.NativeLibrary.free(lpStructure);
			}
			User32.NativeLibrary.free(lpKeywordBuffer);
		}
	}
}
`

**Comment by sieukrem** [comment]
Yes it is possible to start a programm and Chm Viewer in particular. 
[Exec Method of WshShell](https://msdn.microsoft.com/en-us/library/ateytk4a(v=vs.84).aspx)
[Example](https://github.com/sieukrem/jn-npp-plugin/wiki/Helpful-scripts#how-to-save-current-document-with-certain-namepath)

Open Chm-Topic in IE
mk:@MSITStore:<drive:\path\file.chm>::/<topic.htm>
Using this protocol you can access any file in chm via http request (Ajax). 
You can use 7z.exe to see into chm file.

Take a look into *.hhk and *hhc files of you chm file.

Links may be iteresting for you
http://stackoverflow.com/questions/30844427/calling-html-help-from-command-prompt-with-keyword
https://msdn.microsoft.com/en-us/library/windows/desktop/ms524236(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms670172(v=vs.85).aspx
