### ISSUE TITLE
GetModuleHandleW

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#35]
why:

require(require.currentDir+"\lib\Library.js");
var Kernel32 = new Library("Kernel32.dll");
Kernel32.Define("GetModuleHandleW", "LPCTSTR");
hModule=Kernel32.GetModuleHandleW("hhctrl.ocx")
alert(hModule);

return 0?
no problem with f.e.:
hModule=Kernel32.GetModuleHandleW("Kernel32.dll")

**Comment by sieukrem** [comment]
what about x64 and x86?

Try to get last error code
[GetLastError](https://msdn.microsoft.com/de-de/library/windows/desktop/ms679360(v=vs.85).aspx)

**Comment by sieukrem** [comment]
You have to load a module using LoadLibrary before you call GetModuleHandle. Following example works as expected.

```
require("/lib/Library.js");

var Kernel32 = new Library("Kernel32.dll");
var hhctrl = new Library("hhctrl.ocx");

Kernel32.Define("GetModuleHandleW", "LPCTSTR");

hModule=Kernel32.GetModuleHandleW("hhctrl.ocx")

alert(hModule);

```
