### ISSUE TITLE
SC_UPDATE_SELECTION

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#36]
i would to autocopy selection in clipboard.
i tryed:

UPDATEUI:function(v, pos, x){
    if(SC_UPDATE_SELECTION){
        if(currentView.selection!==""){
            System.clipBoard = currentView.selection;
         }
    }
}

but how check SC_UPDATE_SELECTION?

p.s. x64 proceeds?
it would be the first x64 third party plugins.

**Comment by sieukrem** [comment]
you are right there is no way to check what was the cause of UPDATEUI. As workaround you can check the bytePos and byteAnchor to detect any selection change between two UPDATEUI calls.
