### ISSUE TITLE
avoid focus in Editor.createDockable

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#38]
When i write to Editor.createDockable, it get the focus.
Do it is possible to avoid it and mantain focus in editor?
Do it is possible to change background-color in Dockable?
I had hoped x64 in 2.2.183 ;)

**Comment by sieukrem** [comment]
- It is not possible to keep the focus on editor view. You have to set it back . Try following snippet
```
Editor.currentView.pos = Editor.currentView.pos;
Editor.currentView.anchor = Editor.currentView.anchor ;
```
-  Yes, it is possible! Set corresponding css property during creation of dockable (e.g. `css : " body { background-color: #ccc;}"`). Take a look into csslint.js or jshint.js

**Comment by lollita** [comment]
this not set focus to editor for me:
```
Editor.currentView.pos = Editor.currentView.pos;
Editor.currentView.anchor = Editor.currentView.anchor ;
```

this remain white for me:
```
win = Editor.createDockable({
css:"body{background-color:#000}",
docking:'bottom',
```

**Comment by sieukrem** [comment]
Replace Editor.createDockable by the wraper call `new Dialog`. 
```
win = new Dialog({
css:"body{background-color:#000}",
docking:'bottom',
```
You are right. Focus does not change. Some user interaction is necessary :(. Or you use the WinApi

**Comment by lollita** [comment]
When i use "new Dialog" in my script i obtain a "Dialog not defined".
When i use tests.menu.js "css" work in "new Dialog" and not in "createDockable".
Do it is not possible to set background color in a dialog docked?

**Comment by sieukrem** [comment]
1. You can require Dialog.js in your script.
2. Take a look into Dialog.js at its bottom how to use it for dockable dialog
```
win = new Dialog({
css:"body{background-color:#000}",
dockable:{docking:'bottom'}
});
```
3. you don'T need setting of pos and anchor if you use SetFocus

**Comment by lollita** [comment]
ok ty

**Comment by lollita** [comment]
I find MenuCmds.VIEW_SWITCHTO_OTHER_VIEW(); more effective

**Comment by sieukrem** [comment]
yes it works also
