### ISSUE TITLE
removeListener

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#40]
> Use GlobalListener.addListener(yoursCfg); to add new event listener and  GlobalListener.removeListener(yoursCfg); to remove your event listener

but i obtain a method not supported with removeListener.

**Comment by sieukrem** [comment]
GlobalListener is a wrapper written in Javascript. You will find it in start.js. You can implement missed method there

**Comment by lollita** [comment]
In line 7-8 of start.js you write "Use ... GlobalListener.removeListener(yoursCfg); to remove your event listener"
but removeListener is missing.
So I think you should add the removeListener method or remove the line 8.

**Comment by sieukrem** [comment]
Never used - never tested - never implemented
;-)
