### ISSUE TITLE
Library.js patch

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#41]
I have modified Library.js:
- It allows defining types of variables independently of the functions
- It defines variable size for x32 and x64 architecture.
  [Library.zip](https://github.com/sieukrem/jn-npp-plugin/files/520231/Library.zip)
  it is ready for next x64 plugin.

**Comment by KOLANICH** [comment]
@lollita, we are on GitHub. For such proposals you should not post zip archives in issues. You should fork the repo. In the simplest case just [open the file in GitHub for editing](https://github.com/sieukrem/jn-npp-plugin/edit/master/deploy/%5BNotepad++%20Directory%5D/plugins/jN/lib/Library.js) (a pencil button at top right), paste your version into the textarea and click "Propose file change" button in the bottom.

**Comment by sieukrem** [comment]
The x64 version does not support native calls. Some one has to reimplement this feature in assembler for both architectures.
