### ISSUE TITLE
scrollTo bottom a docking bottom

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#42]
How to scroll to bottom a Dialog({dockable:{docking:"bottom"}}?

**Comment by sieukrem** [comment]
Something like this
```
var d = new Dialog({html:"<ol><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li><li>af</li></ol>"
,dockable:{docking:"bottom"}})

d.htmlDialog.document.body.scrollTop+=d.htmlDialog.document.body.scrollHeight;
```

**Comment by lollita** [comment]
When i use it, when the page is full, the background and foreground become white.
to revert right color I have to:
- change foreground application to other and then return to npp
- or select all dialog content, release it and scroll
.
do it is possible to fix it?

**Comment by sieukrem** [comment]
try to do that within System.setTimeout!

**Comment by lollita** [comment]
It work! ty :)
Your plugin is GREAT!!!
i waiting x64 ;)
