### ISSUE TITLE
Some terminal window

### ISSUE THREAD

**Issue by arhangelsoft** [sieukrem/jn-npp-plugin#44]
Greetings!
How I can make a terminal window to launch and listen console apps directly trogth stdin, stdout, stderr?

The Win APIs e.g. CreateProcess requires using the records. Does jN supports them?

**Comment by sieukrem** [comment]
Indeed it is possible to start a process using  WScript.Shell ActiveX from Microsoft. Be aware this API is blocking, you have to read completelly before your script can do something other.

Some days ago I wrote an [example](../wiki/Helpful-scripts#launch-a-program-in-command-prompt).
