### ISSUE TITLE
Scrolling API

### ISSUE THREAD

**Issue by eight04** [sieukrem/jn-npp-plugin#45]
Currently if we set `View.pos` and `View.anchor`, the scroll bar remains its original position even if the caret is out of the window.

Can we have some API like `View.scrollIntoView()` or `View.scrollIntoViewIfNeeded()`? For example, with Ctrl-F, if the caret is out of window, NPP scrolls the scroll bar and put the matched line at the center of the window. With Ctrl-G, NPP scrolls the scroll bar and put the matched line at the top/bottom of the window.

**Comment by sieukrem** [comment]
You can try snippet I posted [here](https://github.com/sieukrem/jn-npp-plugin/wiki/Direct-calls-to-Scintilla#scroll-line-with-cursor-into-visible-view)
