### ISSUE TITLE
Menu definition for Edit > Line Operations > Remove Empty lines?

### ISSUE THREAD

**Issue by fspafford** [sieukrem/jn-npp-plugin#48]
I am wondering if there should be a definition for the subject menu item in this file:

 jn-npp-plugin/deploy/[Notepad++ Directory]/plugins/jN/includes/MenuCmds.js

Regards,
Frank

**Comment by sieukrem** [comment]
Please explain your wish!

**Comment by fspafford** [comment]
I wanted to be able to remove empty lines as part of a new menu routine I created. 

I ended up creating a JavaScript routine to remove the empty lines, since I did not have the ability to invoke the "Remove Empty Lines" from the "Edit > Line Operations" menu.

Thanks for your plugin work,
Frank

**Comment by sieukrem** [comment]
I assume you have a solution now and this issue can be closed?

**Comment by fspafford** [comment]
Yes, I do have a solution. As far as I am concerned, you can close this issue.
