### ISSUE TITLE
Npp+ crash silent with new 32bit version

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#50]
Npp+ crash silent with new 32bit version at the start.
For me only 2.182 work.
Again it support "Library" Unlike 64bit?

**Comment by sieukrem** [comment]
Can You isolate the crash! Die you use it with 64bit Npp?
32bit works only with 32bit

**Comment by lollita** [comment]
I would not know how to isolate because np++ appears briefly and closes itself.

**Comment by sieukrem** [comment]
the 32bit dll from pre-release works on win7 32bit with npp 32bit. Can you check that you not use jn.dll 32bit with npp 64bit!

**Comment by lollita** [comment]
it is obvious that I use 32bit on 32bit and 64bit to 64bit.

**Comment by sieukrem** [comment]
What is the version of npp? I tested with old one.

**Comment by lollita** [comment]
I every last use: 7.3.1

**Comment by sieukrem** [comment]
I tested 7.3.1 (zip deployment) with fresh 2.2.184 on Windows 7 32bit. What is your Windows version?

**Comment by lollita** [comment]
Win 10 64 bit.

**Comment by lollita** [comment]
i mistake to rename old plugin to 2jN.dll instead of jN.dll.bak.
it is a great pity that the library does not work in x64.

**Comment by sieukrem** [comment]
As I understand the issue can be closed
