### ISSUE TITLE
The plugin doesn't work for NPP in Wine

### ISSUE THREAD

**Issue by KOLANICH** [sieukrem/jn-npp-plugin#51]
I use x64 edition, gecko is installed. The only visible effect of your plugin is addition of its submeny into Plugins menu. Everything implemented in JS is missing.

**Comment by sieukrem** [comment]
I think it depends on javascript engine implementation in Wine. Can you check this please!

**Comment by KOLANICH** [comment]
>Can you check this please!
What do you mean by "this"?

**Comment by sieukrem** [comment]
if scripting engine exists for x64 on Wine. I do not use Linux, I cannot verify it.

**Comment by KOLANICH** [comment]
Hmm, it seems WSH for wine is not implemented. ```JScript.dll``` and ```wscript.exe``` and ```cscript.exe``` are present, but it seems they do nothing (I have tried shipped ```cscript.exe`` with a simple test file, the output was empty).

How about dropping this WSH entirely and using [embeddable node.js used in Atom](https://github.com/atom/node) instead? It seems that ActiveX objects can be used in node with help of [node-win32ole](https://github.com/idobatter/node-win32ole).

**Comment by sieukrem** [comment]
Is it possible that cscript.exe runs as win32 application in wine environment? If so then you have to run win32 version of npp with x86 verision of jn.dll.

You are right. Today if I would have to decide which engine I want to use I would take V8. But today there are a lot other good Editors like Visual Studio Code using V8. VSC has huge growing community and support from Microsoft side. It would be waste of time if I would begin to integrate V8 into Npp :-(.

I like N++ as fast and "lightweight" text editor with nice scripting API via jN.

**Comment by KOLANICH** [comment]
>VSC has huge growing community and support from Microsoft side.
But today there are a lot other good Editors like Visual Studio Code using V8. VSC has huge growing community and support from Microsoft side. It would be waste of time if I would begin to integrate V8 into Npp :-(.

If VSC a replacement for NPP, it means that NPP is not needed. But VSC is not. VSC is a memory-hungry yet another Electron app with [integrated surveillance](https://www.microsoft.com/en-us/privacystatement/EnterpriseDev/default.aspx). So NPP is needed. Maybe there is a need in something like WebExtension, but for text editors.

Also, I [have some ideas](https://github.com/mikaelbr/open-source-ideas/issues/45) about embedding JS engines. This particular idea was inspired by your plugin. If you decided to change a JS engine, it may worth to implement it first.

**Comment by KOLANICH** [comment]
Any progress on this issue?
