### ISSUE TITLE
Remove menu items?

### ISSUE THREAD

**Issue by Fabian42** [sieukrem/jn-npp-plugin#52]
Is it possible to remove "preinstalled" menu items (like "Window") with this?
And is there a documentation I can see without installing the plugin first? When I search for "api.xml" in this repository, I don't find it.

**Comment by KOLANICH** [comment]
"Preinstalled" menus are in fact defined in JS files. Use NPP ```Find in files``` feature to find the file defining the menu you are interested in removing of.

**Comment by sieukrem** [comment]
Do you mean with "preinstalled" the native Notepad++ menu items? If 'yes' then it is not possible directly. If 'no', you can follow the sugestion from KOLANICH.

if 'yes' then you can try the [Win32 API](../wiki/Calling-of-Win32-API-functions) way.


The documentation is on the [wiki page](../wiki). The API.xml works only if you copy [/plugins/jN/API](../tree/master/deploy/%5BNotepad%2B%2B%20Directory%5D/plugins/jN/API) folder on you PC.
