### ISSUE TITLE
byteStart wrong on large file

### ISSUE THREAD

**Issue by lollita** [sieukrem/jn-npp-plugin#54]
In very large file "byteStart" return wrong value, instead "start" work fine.

**Comment by sieukrem** [comment]
What does "wrong" mean? Is it unicode utf-8 file?

----- Ursprüngliche Nachricht -----
Von: "Diamanti" <notifications@github.com>
Gesendet: ‎29.‎04.‎2017 19:57
An: "sieukrem/jn-npp-plugin" <jn-npp-plugin@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [sieukrem/jn-npp-plugin] byteStart wrong on large file (#54)

In very large file "byteStart" return wrong value, instead "start" work fine.

**Comment by lollita** [comment]
f.e. it return position "1" when it is "6".
Yes it is unicode utr-8 file. Converted to ansi and problem disappareid.

**Comment by sieukrem** [comment]
I would expect that byteStart returns 6 and start returns 1. 

Do you know the difference between 'byteStart' and 'start'?

The 'byteStart' is fast way to get the position without regarding to characters count. The 'start' translates byte position to character position and is 'slow' operation.
