### ISSUE TITLE
ClearCase not working since 2.2.182

### ISSUE THREAD

**Issue by gpxricky** [sieukrem/jn-npp-plugin#57]
The ClearCase context menu does not appear anymore since release 2.2.182. It worked fine for me for version 2.1.181.

**Comment by sieukrem** [comment]
1. Move clearcase.js from [Notepad++ Directory]/plugins/jN/includes/disabled to [Notepad++ Directory]/plugins/jN/includes
2. Restart Notepad++

**Comment by gpxricky** [comment]
Worked perfectly, thank you very much.
