### ISSUE TITLE
Some enums and a script to be added

### ISSUE THREAD

**Issue by KOLANICH** [sieukrem/jn-npp-plugin#58]
Here is the script enabling better font rendering (needed to make ligatures and kerning work)
```javascript
require("lib/Scintilla.js")
Scintilla.prototype.Const.SCI_SETTECHNOLOGY=2630;
Scintilla.prototype.Const.SCI_GETTECHNOLOGY=2631;
Scintilla.prototype.Const.SC_TECHNOLOGY_DEFAULT=0;
Scintilla.prototype.Const.SC_TECHNOLOGY_DIRECTWRITE=1;
Scintilla.prototype.Const.SC_TECHNOLOGY_DIRECTWRITERETAIN=2;
Scintilla.prototype.Const.SC_TECHNOLOGY_DIRECTWRITEDC=3;
var sci = new Scintilla(currentView.handle);
sci.Call("SCI_SETTECHNOLOGY", Scintilla.prototype.Const.SC_TECHNOLOGY_DIRECTWRITE, 0);
```

1 I guess the enums from it should be added into Scintilla.js
2 I guess the script should be added into the repo 

BTW: require causes error.

**Comment by sieukrem** [comment]
I have integrated the new constants and added a snippet showing how to use them on [wiki](../wiki/Direct-calls-to-Scintilla)

**Comment by KOLANICH** [comment]
>I can recognize the difference between them and I like the default one :).

In fact the default one has drawback - ligatures such as in Fira Code don't work. It's a shame that NPP doesn't have the switch in the settings built-in. That snippet is just a port of the [lua one](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287#issuecomment-256638098).

**Comment by KOLANICH** [comment]
Also the script throws an exception. `require` doesn't work correctly. At least on my system.

**Comment by sieukrem** [comment]
What error do you get?
Did you compare the implementation of *require* in *start.js*

**Comment by KOLANICH** [comment]
>What error do you get?

I'll test tommorow. Now I'm from a phone.

>Did you compare the implementation of require in start.js

In fact I don't remember. I did some tests (if I remember right, I have even temporarely replaced my forked version with the version from this repo), but I don't remember well.

**Comment by KOLANICH** [comment]
I have checked. That was my fault. I have screwed up some things. Now they are fixed.
