### ISSUE TITLE
Is it possible to output text in the Status bar?

### ISSUE THREAD

**Issue by trdm** [sieukrem/jn-npp-plugin#60]
It is necessary to inform about slow processes. 
Yes, and in general this opportunity will be very useful.

**Comment by sieukrem** [comment]
I did not find any Notepad++ API for this purpose. You can try to use native WinApi calls to find and modify statusbar text. Or you can build a Html based  dialog and show it during long processes

**Comment by trdm** [comment]
It's a bit difficult for me.
6-7 years did not write on winapi. Now I'm working on Intellisense for js and vbs scripts and I'm counting on a certain plugin functionality to make Intellisense work more user-friendly.
https://prnt.sc/hu411b - Intellisense for js work.

**Comment by sieukrem** [comment]
Solved by [2.2.185.1](../releases/tag/2.2.185.1)
Find an example in [Wiki](../wiki/Helpful-scripts#change-the-text-of-statusbar) article.

**Comment by trdm** [comment]
Very good! Thank you!

**Comment by trdm** [comment]
Relatively. require ("lib / Window.js"); 
https://github.com/sieukrem/jn-npp-plugin/wiki/Helpful-scripts#change-the-text-of-statusbar
in the DOM in browsers there is a "window" object. Your Window object. 
Visually, the code merges.

**Comment by sieukrem** [comment]
I don't see any problem! It depends on some one's programming style. :-)

The Window **class** I have defined should never be used with window **object** from browser in the same script file. They come from different worlds. If one have to use them together, then one have to bring them on the next level of abstraction. For example by using of concrete instance of Window for accessing statusbar of Notepad++ in a composit object.
```
function NppStatusbar(){
   this.StatusBar = Window.FindByClass(Editor.handle, "msctls_statusbar32");
}
NppStatusbar.prototype.SetText = function(text){ this.StatusBar.SetWindowText(text)}
NppStatusbar.prototype.GetText = function(){ return this.StatusBar.GetWindowText()}
NppStausbar.Instance = new NppStatusbar();
```
