### ISSUE TITLE
The necessary information about which script was the one in which the error occurred.

### ISSUE THREAD

**Issue by trdm** [sieukrem/jn-npp-plugin#61]
The report on the cone is extremely uninformative. See Attachment.
http://prntscr.com/hv3toe
The file name is required.

**Comment by sieukrem** [comment]
What are you missing? It is a message from JavaScript Engine not from the jN Plugin!

**Comment by trdm** [comment]
I will be grateful!
Make https://github.com/sieukrem/jn-npp-plugin/issues/60 please, because there's only a window to find by class and a message to send the toolbar with the text setting.
http://prntscr.com/hv55w7

**Comment by sieukrem** [comment]
Solved with [2.2.185.2](../releases/tag/2.2.185.2). 

Please verify whether something was brocken by this solution

**Comment by trdm** [comment]
I confirm, thank you for resolving the issue!
Good work, I'm generally on the plugin and scripts :)
Кстати, ты же русский вроде знаешь, можем общаться по аське или по скайпу?

**Comment by sieukrem** [comment]
I will close this issue then, and if you or some one else do not find any bugs in few days I will declare this release as a latest release.

Да я знаю русский, но думаю формат GitHub и этот проект предполагают общение на английском. Аська и скайп для меня вымерли. Я предпочитаю E-Mail для деловых отношений, а для проектов в основном Issues/Workitems. Это позволяет лучше организовывать свободное и рабочее время.

**Comment by trdm** [comment]
Hi! 
If an error of this type can determine the file name and string? And get them out.
http://prntscr.com/hwfe6h

**Comment by sieukrem** [comment]
How can I reproduce this error?

**Comment by trdm** [comment]
Approximately so, but now I can not catch, tk. remade the script.
It is necessary to execute the script:
function test_error(){
	var wd = 'trim(Line';
	var patern = wd+"\\s*([a-z\\.+]*)";
	var patern = wd+"\\s*([a-z\\.+]*)\\s*ActiveXObject"+wd;
	var reNew = new RegExp(patern, 'img');
}
test_error();

**Comment by trdm** [comment]
Caught the situation with an error.
Steps to reproduce:
Intell.js
Row 145:
vPartLine // to reproduce the error, enter a dot "."
The file with the contents of the directory jN.
https://yadi.sk/d/XC8yGa6O3RF2gY 

screenshot http://prntscr.com/hx4to0

**Comment by trdm** [comment]
a curious mistake caught. Also not reported line number and file.
code in the screenshot.
screenshot: http://prntscr.com/hx9k5w

**Comment by sieukrem** [comment]
I think the problem with missed file name is that Script Engine distinguish between errors during first parsing+execution and errors during execution. For example you run the script first time. The function definitions are done but not run yet. Later some action lets run our function causing the error. This error will be catched inside of script. In such case the script engine doese not notify the host. So that the host can not find file causing error and show this in a messagebox.
