### ISSUE TITLE
Ошибка с непонятным указанием на место возникновения.

### ISSUE THREAD

**Issue by trdm** [sieukrem/jn-npp-plugin#62]
http://prntscr.com/i1o71o
Если указываешь:
require("lib/User32.dll.js"); 
То все норм.
ПС. Спасибо за функционал require("lib/User32.dll.js");  - очень выручает. 
Хотя все равно не особо понял как параметры передавать.

**Comment by sieukrem** [comment]
Я не понимаю в чём загводка. 
Сообщение укаывает правильно на [место ](../blob/80da72e5abaef55b1c2096d5d867e630038d057c/deploy/%5BNotepad%2B%2B%20Directory%5D/plugins/jN/start.js#L155)где было брошено исключение.

**Comment by trdm** [comment]
Программируя в разных средах, привыкаешь к разному поведению. Где-то система сразу указывает на строку, вызвавшую ошибку, а где-то система указывает на обработчик.
Закрывай вопрос. Проблема победима.

**Comment by KOLANICH** [comment]
Возможно, что для решения этой проблемы нужен нормальный движок JS со встроенной поддержкой require, которого по ходу не будет.

**Comment by trdm** [comment]
Я как то мельком нарывался на такую проперть функции как caller.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/arguments/caller
Возможно эта проперть как-то поможет решать подобные проблемы.

**Comment by sieukrem** [comment]
require реализована на javascript поэтому исключение идет глубже по стеку как если бы это была нативная реализация
