### ISSUE TITLE
Есть некая проблема с назначением хоткеев.

### ISSUE THREAD

**Issue by trdm** [sieukrem/jn-npp-plugin#63]
Проблема в выборе хоткея для скрипта и его назначении. Дело в том, что часто хоткеи уже назначены и переназначая хоткей просто вырубаешь команду.
Как у меня было с "Ctrl+I" который уже назначен команде "Правка"->"Cтроки"->"Разбить строки Ctrl+I".
Можно как-то контролировать назначаемый хоткей и предупреждать о его использовании. 
А лучше всего генерировать список комманд из всего меню, в котором можно найти хоткей поиском. Т.е. желателен метод плагина, который генерирует текст, нечто вроде:
Файл->Новый\tCtrl+N
Файл->Открыть\tCtrl+O
Этот текст можно использовать для поиска свободного хоткея.
Понимаю, проблема не для этого плагина, но как-то с этим надо разбираться.

**Comment by sieukrem** [comment]
You are right the Hotkey issue is not realy the problem of jN, but Notepad++Hotkey API. It has declarative character. Hence it was not the option to use it in jN. jN provides imperative way to assign hotkeys.

If you do your own application based on Notepad++ you can write a wrapper for jN API catching assignments of hotkeys and track them in a table, with the possibility to reassign them using own html based dialog.

As you already assumed I can't help in this case. It is another abstraction layer. You can do a pull request by Notepad++ or feature request to offer an imperative API.

**Comment by trdm** [comment]
Есть плагин, https://sourceforge.net/projects/nppmenusearch/ - он решает подобную проблему.
Написан на C#, разобраться что он делает можно. Попробую повторить его часть с пом. твоего плагина и его возможностей.
Однако при этом он бьет *.dat - файл с избранным в N++, так что пользоваться этим плагином невозможно лично для меня.

**Comment by trdm** [comment]
Есть возможность с пом. твоего плагина встраивать справку в N++.
Интересует? Справка по php, js, vbs и т.п.
Немного геморно, но возможность я реализовал с пом. 
var option = {name:'Документация',docking:'right', onclose:function(){	gHelpWindow = '';}};	
gHelpWindow = Editor.createDockable(option);
Суть в чем: есть chm-файл со справкой. Он разбирается с пом. утилиты chm2html, в каталоге есть файл индексный файл *.hhc, я его парсю и вывожу в формате для построения дерева:
d.add(0,-1,'Справка');
d.add(1,0,'Automatition','"','','docs');
d.add(2,1,'Некоторые объекты Automation','html/Automatition/HTML/Automation.html','','docs');
d.add(3,2,'Объект Shell','html/Automatition/HTML/ObjectShell.html','','docs');
а потом просто атачу в html. Полчается страница с 2-мя фреймами. В верхнем дерево документации, разбитое по разделам, а в нижнем выводится сама станица справки.
Однако столкнулся с проблемами. 1-я проблема: я не знаю как навигировать нижний фрейм из скрипта jN. Это нужно для контекстной справки: нажал хоткей и справка должна навигироваться на нужную страничку. Страничку найти легко, а вот с навигацией проблемы.
Проблема 2-я: генерация дерева происходит в скрипте и чем больше документации подключаешь, тем больше скрипт, и тем больше тормозит начальная генерация.
В итоге вылазит: http://prntscr.com/ib9f64 и приходится жать на батон [нет].
Проблема-3: коллекция справки хренов работает, если лежит в каталоге, где в пути есть "++" или пробелы. По этому коллекцию и скрипты приходится переносить из папки в другое место. А это несет немгого неразберихи.
В идеале GUI дерева переписать на winapi, а нижний фрейм оставить под MS IE.
В итоге получилось вот что: 
https://github.com/trdm/jn-npp-scripts/blob/master/Doc/jN-help1.gif

**Comment by trdm** [comment]
Относительно проблемы http://prntscr.com/ib9f64 мне подсказали на одном из ресурсов возможное решение проблемы. Надо объекту IWEBBrowser выставить свойство slient в true.
Из скрипта я это не могу сделать, разумнее всего дополнить параметр cfg метода createDockable свойством slient с возможностью его установки.

**Comment by sieukrem** [comment]
I can't answer to all of questions in this thread. Please open different issues for differen questions or problems

**Comment by sieukrem** [comment]
You can navigate HTML based dialog into chm file without decompiling it 
mk:@MSITStore:E:\dirrrr1\dirrrr2\helppppppfile.chm::/htmllllllfileeeeinside.html

CHM file is like ZIP file. There is an addon in 7zip which is able to decompile chm. So you can use it to discover the name of .hhc file.

The issue with TOC is not really the problem of slow javascript. It is never good idea to display all of entries. You have to use lazy inserting of child entries on opening of parent entry. Works very good also on huge TOCs.

Silent flag does not solve the rootcause but hides it, what results in negative user experience (Notepad++ is hanging)

**Comment by trdm** [comment]
Благодарю за ответ. Просто использовал  старую уже готовую js библиотеку для построения дерева, которая бы поддерживала бы минимум IE6. В ней нет ленивой загрузки. Прийдется переписать библиотеку.
Но похоже я самого главного не достигну, если буду использовать веб-страничку с: 
<frameset rows = "50%, 50%" border = "6">
	<frame src = "dtree.html">
	<frame src = "b_frame.html" name = "docs">
</frameset>
мгновенная навигация к нужной странице во фрейме "docs". Мне или прийдется переформировавывать страничку с фреймами, либо искать другой путь.

**Comment by sieukrem** [comment]
[Example ](/sieukrem/jn-npp-plugin/blob/80da72e5abaef55b1c2096d5d867e630038d057c/deploy/%5BNotepad%2B%2B%20Directory%5D/plugins/jN/includes/Dialog.js#L61)of accesing elements in the html dialog

**Comment by trdm** [comment]
Это не поможет управлять содержимым frameset. Увы, но там стоит защита.

**Comment by trdm** [comment]
Вот как это должно работать: https://github.com/trdm/jn-npp-scripts/blob/master/Doc/vi_2.gif

**Comment by trdm** [comment]
Решил проблемы.
- доработав один из шпионов (https://www.codeproject.com/Articles/42780/UI-Control-Data-Spy) http://prntscr.com/ljrkab
- Использовал плагин: LanguageHelp https://sites.google.com/site/fstellari/nppplugins
Правда пришлось перепаковать несколько chm-ok, создать поисковые индексы. Поимел кучу геморроя :) ( http://prntscr.com/ljrlmz )
Вопрос можно закрывать.
