### ISSUE TITLE
The link to Windows Script Debugger is offline

### ISSUE THREAD

**Issue by eight04** [sieukrem/jn-npp-plugin#65]
The wiki page:
https://github.com/sieukrem/jn-npp-plugin/wiki/Debugging

Windows Script Debugger:
http://www.microsoft.com/de-de/download/details.aspx?id=1757

**Comment by sieukrem** [comment]
Microsoft does not support and does not offer the tool for download anymore.

**Comment by eight04** [comment]
BTW, I haven't used Visual Studio before. Which workloads/components are required to debug windows scripts?

**Comment by trdm** [comment]
> BTW,  I haven't used Visual Studio before. Which workloads/components are required to debug windows scripts?

As a part of MS Offices there is usually MSE, you just have to remember to opt out. If you have an office installed, you can try to find mse.exe and register it as a debugger.
And call it directly from N ++ ka shown in the picture.
http://prntscr.com/ir1n19

**Comment by trdm** [comment]
@sieukrem 
I am helped in debugging scripts such a solution:
IntellUntil.js

`var gMessageWindow = null;
var gMessageDocum = null;

//{trdm: 2018-02-28 13:20:36
function createMessageWindow() {
	var option = {		
		name:'Сообщения (Закрыть: Ctrl+Shift+Z):',		
		docking:'bottom', 
		onclose:function(){
				gMessageWindow = '';
				gMessageDocum = '';
			}
		};	
	gMessageWindow = Editor.createDockable(option);
	gMessageDocum = gMessageWindow.document;
	// ul{margin-left: 20px;} - виден маркер ul{margin-left: 3px;} - не виден
	strDoc = '<html><head><style type="text/css">body{font-size: 14px; font-family:courier ; margin: 2px; padding:2px;} ul{margin-left: 3px;}</style> '+
	'</head><body><UL id="main"></UL></body>';
	gMessageDocum.write(strDoc);
}

// using: message('bla-bla-bla');
function message(psStr) {
	if(!gMessageWindow) {
		createMessageWindow();
    }
	if(gMessageDocum) {
		var main = gMessageDocum.getElementById("main");
		var p = gMessageDocum.createElement('li');
		p.innerText = psStr;// + 'dlh.handle = ' + gMessageWindow.handle;
		main.appendChild(p);
    }
}
function EditorMessage(psMessage) {	message(psMessage); }
function EditorMessageDT(psMessage) {	
	var Today = new Date;
	var dts = formatData(Today,'yyyy-MM-dd HH:mm:ss');
	message(dts+' '+psMessage); 
}

function CloseMessageWnd() {
	if(gMessageWindow) {
		gMessageWindow.visible = false; // это работает
		gMessageWindow.close();
		gMessageWindow = '';
		gMessageDocum = '';
    }
}

var myCloseMessageWndCommand = {
    text: "Закрыть окно сообщений \tCtrl+Shift+Z", 
    ctrl: true,    shift: true,    alt: false,
    key: 0x5A, // "F1"
    cmd: CloseMessageWnd	
};

addHotKey(myCloseMessageWndCommand); 
scriptsMenu.addItem(myCloseMessageWndCommand);
`
using:
```
	message('Hello!');
	message('Hello!-2');
	message('Пример 2. Использование :before и content');
	EditorMessageDT('<- Строка с датой и временем. ');
	EditorMessage('bla-bla-bla');

```

**Comment by eight04** [comment]
My question is about the installation of Visual Studio. I'm not sure which one should be installed.
![image](https://user-images.githubusercontent.com/1324510/37401510-3612c996-27c3-11e8-81e4-123996a0d8b8.png)

**Comment by trdm** [comment]
It sounds strange, but when installing MS VS for with ++ debugging scripts works fine.
But the first package of UWPD can help.

**Comment by sieukrem** [comment]
If you don't need VS itself, then install the smallest set which is possible. For example .Net Desktop development.

**Comment by eight04** [comment]
I have installed ".NET desktop development" workload but there is no "script" code type.
![image](https://user-images.githubusercontent.com/1324510/37536942-000f1dca-2987-11e8-8271-387e01a0a12a.png)
![image](https://user-images.githubusercontent.com/1324510/37536977-206dc698-2987-11e8-8536-bce1427873d6.png)
Any suggestion?
![image](https://user-images.githubusercontent.com/1324510/37537129-93c528ac-2987-11e8-8df9-a9b5940a9502.png)

**Comment by eight04** [comment]
It ends up with these components:
![image](https://user-images.githubusercontent.com/1324510/37544409-d818ef9e-299f-11e8-9fea-6811f92e295d.png)
* TypeScript 2.6 SDK: required by "JavaScript and TypeScript language support".
* JavaScript and TypeScript language support: make VS support "Script" code type.
* Just-in-Time debugger: [spawn VS from notepad++ by running `debugger;` statement](https://prnt.sc/ir1n19).
