### ISSUE TITLE
About dialog displays no longer available domain

### ISSUE THREAD

**Issue by HelderMagalhaes** [sieukrem/jn-npp-plugin#68]
When opening the About dialog (_Plugins_ --> _jN Notepad++ Plugin_ --> _About_) the following dialog is presented:
![image](https://user-images.githubusercontent.com/557924/41193848-63b597d0-6c0a-11e8-919a-5d23643f8db8.png)

This refers to _softwarecanoe.de_, which is a domain (currently) not available.

Suggestion: Update to the link displayed in the plug-in manager (https://github.com/sieukrem/jn-npp-plugin/wiki)

**Comment by AakaFosfor** [comment]
Looks like fixed in 94cb022ba621919847a6c179d2c99133562e884e. Close?
