### ISSUE TITLE
Digitally sign all the binaries

### ISSUE THREAD

**Issue by KOLANICH** [sieukrem/jn-npp-plugin#70]
For example with GPG (please note that you need a way to authenticate your public key somehow, because if anyone can claim that he is you, the security properties don't hold.).

**Comment by sieukrem** [comment]
Is that required by npp?

**Comment by KOLANICH** [comment]
No.

**Comment by sieukrem** [comment]
Why the effort and additional risk because of private key somewhere in the cloud for me?

**Comment by KOLANICH** [comment]
>because of private key somewhere in the cloud

What the problem to build on own PC and sign on it?

**Comment by KOLANICH** [comment]
have you done this?

**Comment by sieukrem** [comment]
No! It is no issue, but feature request. It is not possible to realize via
some automatic buils pipeline now.

KOLANICH <notifications@github.com> schrieb am So., 14. Juli 2019, 23:02:
