### ISSUE TITLE
how to use jquery.js in Dialog's html?

### ISSUE THREAD

**Issue by china-qd** [sieukrem/jn-npp-plugin#73]
- my code:
    var script = theDocument.createElement('script');
    script.setAttribute('type', 'text/javascript');
    script.setAttribute('src', require.currentDir + '\\lib\\jquery-3.3.1.js');
    var headRef = d.getElementsByTagName('head')[0];
    headRef.appendChild(script); 

- my env:
    windows10, IE11, NPP-portable-v7.6 64bit

- then it show the same error as: 
https://stackoverflow.com/questions/27238135/script-error-with-loading-jquery-in-iwebbrowser2

![TKBXh](https://user-images.githubusercontent.com/3890550/54379862-38fb3680-46c5-11e9-9907-4b7da911c83a.png)

- but no errors occurs when i write a simple js instead of jquery.js......

**Comment by KOLANICH** [comment]
>how to use jquery.js

One mustn't use any shit like JQuery, Angular, React, Bootstrap or Vue.

**Comment by sieukrem** [comment]
I can only presume, because I never used jQuery inside of the Dialog. But I think it depends on the expectations of the jQuery that it runs inside of proper Browser. The Browser exposes some properties like *window* to the javascript running inside.

You can try to use the IExplorer directly as ActiveX
```javascript
var ie = new ActiveXObject("InternetExplorer.Application");
ie.Visible = true;
ie.AddressBar = false;
ie.Navigate("http://google.com");
```

Take a look into [InternetExplorer API](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752084(v%3Dvs.85))

**Comment by china-qd** [comment]
> trusted
not loading scripts from Internet but from {jN}/lib/***.js

**Comment by china-qd** [comment]
@sieukrem 
3Q. i think so. some of the properties that jquery dependenced are not exposed. 
i will a simple selector instead of jquery.

**Comment by KOLANICH** [comment]
>not loading scripts from Internet but from {jN}/lib/***.js

OK.

But using the frameworks and libs like JQuery is not OK. They are slow and resource-consuming. I never understand why do developers use them instead of Vanilla JS.

**Comment by china-qd** [comment]
@KOLANICH 
3Q. greate.
i choose jquery, beacause it is quikly to select dom element, attach events and adapted for many browsers.

**Comment by KOLANICH** [comment]
>quikly to select dom element

https://developer.mozilla.org/ru/docs/Web/API/Document/getElementById

>attach events

https://developer.mozilla.org/ru/docs/Web/API/EventTarget/addEventListener


Available in all browsers, even IE6.

Also

https://developer.mozilla.org/ru/docs/Web/API/Document/querySelectorAll , available in all modern and mostly all unmodern browsers - it has been there for more than a decade.

**Comment by trdm** [comment]
@china-qd, 
What problem do you solve?

**Comment by china-qd** [comment]
thanks all.
@trdm i just want use jquery in jN's Dialog, but jquery cannot run in jN's Dialog(IWebBrowser2). code is:
var dialog = new Dialog({
    npp: Editor,
    css: '',
    html: '\<div>\<img src="xxx1" />\<img src="xxx2" /></div>',
    Height:380,
    Width:680,
    Top: 200,
    title: "sort dlg",
    oncreate: function() { // this==the document
        var jqueryPath = require.currentDir + '\\lib\\jquery-3.3.1.js';
        
        // add jquery.js to document. but can not run correct
        var script = this.createElement('script');
        script.setAttribute('type', 'text/javascript');
        script.setAttribute('src', jqueryPath);
        var headRef = this.getElementsByTagName('head')[0];
        headRef.appendChild(script); 
        
        var $ = this.parentWindow.$; // i just want use jquery's $.
        alert( $('div img').attr('src') );
    },
    
});
dialog.show();

**Comment by china-qd** [comment]
finally, tinyjs seems OK. http://tinyjs.sourceforge.net/index-en.html
