### ISSUE TITLE
Call to win32 functions not working

### ISSUE THREAD

**Issue by David-Mawer** [sieukrem/jn-npp-plugin#79]
Hi There,

So I love being able to write my own scripts that execute in np++ as normal menu options.

I'm trying to use the win32 libraries now (using the example in this page: https://github.com/sieukrem/jn-npp-plugin/wiki/Calling-of-Win32-API-functions
)

I can't get that example to work at all - below is the code I'm using: -

	testMenu.addItem({
		text:"Testing MessageBox",
		cmd:function(){
			var lib = System.loadLibrary("user32.dll");
			
			var paramBuf = lib.alloc( 4 * 4);
			var myText = 'Functionality not yet implemented';
			var myCaption = 'Custom Caption :-)';

			lib.writeDWord(paramBuf, 0,  0);
			lib.writeDWord(paramBuf, 4,  myText);
			lib.writeDWord(paramBuf, 8,  myCaption);
			lib.writeDWord(paramBuf, 12, 0);

			lib.call('MessageBoxW', paramBuf);
		}
	});

Please could you let me know what I'm doing wrong?

Thanks :-)

**Comment by sieukrem** [comment]
Hi David,

Which OS and Platform (x64, x86) are you using.

Which  Npp version (x64 x86).

Which error message do you get.

Can you provide entire code you try to run.

With regards
Eugen

David Mawer <notifications@github.com> schrieb am Do., 29. Aug. 2019, 17:41:

**Comment by David-Mawer** [comment]
Hi Eugen,

OK - so I'm running windows 10 Pro (x64)

and Npp v7.7.1 (x64)

I don't get any error message when the code runs.


[DavidMenu.txt](https://github.com/sieukrem/jn-npp-plugin/files/3558530/DavidMenu.txt)

I've attached the file from my "**plugins\jN\jN\includes**" folder ( had to rename it to a .txt file for GitHub to accept it).

Thanks,
David :-)

**Comment by sieukrem** [comment]
Hi David,

Win32 calls are working only in Nppx86.

I did not have time to adapt asm code working for parameter passing in x64.
It could be also breaking change in the JN api necessary.

So my advice is to use x86 version of npp if you need win 32 calls.

With regards
Eugen

David Mawer <notifications@github.com> schrieb am Fr., 30. Aug. 2019, 08:29:

**Comment by David-Mawer** [comment]
OK, thanks :-)
