### ISSUE TITLE
jN plugin manager

### ISSUE THREAD

**Issue by zuenko-mikhail** [sieukrem/jn-npp-plugin#83]
I wrote a script manager for jN Notepad++ Plugin.

![Screenshot](https://user-images.githubusercontent.com/62737813/78119930-5d8e9180-7433-11ea-89cd-d233920bd12c.png)

**Can be downloaded in English and Russian**:
[Script manager (English).zip](https://github.com/sieukrem/jn-npp-plugin/files/4414075/Script_manager_.English.zip)
[Script manager (Russian).zip](https://github.com/sieukrem/jn-npp-plugin/files/4414076/Script_manager_.Russian.zip)

**Comment by KOLANICH** [comment]
You should better to publish the English version as a PR to this repo.

**Comment by sieukrem** [comment]
@zuenko-mikhail First of all I appreciate the idea and your work.

But I agree with @KOLANICH 
> You should better to publish the English version as a PR to this repo.

* The English version only will simplify support/development of the manager
* A pull request will speed up diskussions and the integration of the manager

**Comment by depascalis** [comment]
This script pulls files from a Russian server, not ok! Probably not malicious intent, but still...

**Comment by trdm** [comment]
> This script pulls files from a Russian server, not ok! Probably not malicious intent, but still...

If it bothers you, then you should edit the script. Greetings from Russia.

**Comment by depascalis** [comment]
Nothing against Russia, but there is lots of crap from Russian servers, I just wanted to make people aware. Stay safe ♥️

**Comment by sieukrem** [comment]
@depascalis thanks for attention! 
I will close the issue. Independently from origin the file looks suspicious and request to open pull request was ignored.
