### ISSUE TITLE
Copying jN folder/dll file does not make the plugin menu items appear

### ISSUE THREAD

**Issue by mahaju** [sieukrem/jn-npp-plugin#84]
I have used the plugin for a long time now and have been satisfied with it

I mainly use it for the feature where it shows all relative locations of a highlighted word in that document as a coloured point in the vertical bar (like in google chrome word search, please see this post for the feature I am talking about: https://softwarerecs.stackexchange.com/questions/15083/google-chrome-like-word-search-in-notepad)

However, I downloaded the latest version from here: https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.6, and copied the jn folder and dll file as shown here: https://github.com/sieukrem/jn-npp-plugin/wiki/How-to-start, but I cannot see the plugin in the menu

I went to Notepad++'s plugin installer and I think it has 2.2.185.5, and once I install it I can see all the menu items as well, but when I highlight a word I cannot see other locations of the word in the vertical scroll bars. The last time I installed this was a long time ago and I don't remember everything I did, but as far as I remember, I just had to copy the dll files and restart notepad, and the plugin had started working, but it is not happening with the latest version. Is this a bug or did I do something wrong? I am mostly interested in the feature where the vertical scroll bars show the relative locations of a highlighted word.

Windows version is Windows 10 Pro 1903 64 bit, Notepad++v7.7.1 64 bit.

**Comment by sieukrem** [comment]
Please check comments in #74. 

I think the best approach for you is to install old version of jN through the plugin manager and than replace the jN.dll from the newest jN release.

**Comment by sieukrem** [comment]
I assume that newest Npp version expects additional directory for every plugin.
You can try to put the entire content of newest jN version zip into `plugins/jN`
so that it is like follows 
```
/Notepad++/plugins
  |-/jN
       |-/jN
       |-jN.dll
       |-readme.txt  

```

**Comment by nicmonson** [comment]
I am facing a similar issue to @mahaju. I tried installing the plugin via the latest version listed here (2.2.185.6) as well as through the Notepad++'s plugin installer each on a different machine. In both attempts, I do see the vertical bar as well as the menu items. Double-clicking on a word to highlight it or searching for that word does not cause the word to show up on vertical bar however UNLESS I click on another tab and then click on that tab. I am guessing the function that refreshes the right bar is not updated by click stuff but is updated when switching tabs. This is my first time trying this plugin for notepad++ so I don't know when this might have stopped working. Thanks!

**Comment by sieukrem** [comment]
> I am facing a similar issue to @mahaju. I tried installing the plugin via the latest version listed here (2.2.185.6) as well as through the Notepad++'s plugin installer each on a different machine. In both attempts, I do see the vertical bar as well as the menu items. Double-clicking on a word to highlight it or searching for that word does not cause the word to show up on vertical bar however UNLESS I click on another tab and then click on that tab. I am guessing the function that refreshes the right bar is not updated by click stuff but is updated when switching tabs. This is my first time trying this plugin for notepad++ so I don't know when this might have stopped working. Thanks!

Did you try to replace the content as I described in [comment](#issuecomment-609967584)?

**Comment by nicmonson** [comment]
Yes, I do have it inside a jN folder as you described. 
If one installs plugins via Notepad++'s plugin installer, it naturally puts in the right spot as you noted in your in your comment. When I manually tried to install your plugin by downloading from your github page, I did put it in the manner you requested. I initially did it the wrong way and did not even see the column on the right. Reading the comment of @mahaju, one can tell that he did not have the folder in the right position for his manual install but did get it in the right spot when using the Notepad++ plugin installer.

**Comment by mahaju** [comment]
Here is what is currently working for me:

> Please check comments in #74.
> 
> I think the best approach for you is to install old version of jN through the plugin manager and than replace the jN.dll from the newest jN release.

I have done what @sieukrem mentioned in this quote 
I initially installed the older version from the plugin manager and just replaced the dll file from the latest zip  

![github_01](https://user-images.githubusercontent.com/1299251/83654620-5a14b380-a5f8-11ea-9e39-a6c27b472994.png)
