### ISSUE TITLE
user js function setInterval() has error

### ISSUE THREAD

**Issue by 13406169210** [sieukrem/jn-npp-plugin#85]
I’ve defined a method that essentially jumps the cursor to the specified line

`	function jumpLine(){
		currentView.lines.current+=2;
	}
	
	var jump = {
		text:"jump",
		ctrl:true,
		key:116,	
		cmd:function(){
			addScript(setInterval(jumpLine(),1000));
		}
	}
	
	runMenu.addItem(jump);
	addHotKey(jump);`

But this is called only once, and an error is reported

If used in this way, report an error directly

`	function jumpLine(){
		currentView.lines.current+=2;
	}
	
	var jump = {
		text:"jump",
		ctrl:true,
		key:116,	
		cmd:function(){
			addScript(setInterval(jumpLine,1000));
		}
	}
	
	runMenu.addItem(jump);
	addHotKey(jump);`

please pay attention to "jumpLine" and "jumpLine()"

Friends who can help me, thank you

**Comment by sieukrem** [comment]
If your goal only the jump is then replace the line with add addscript.... by jumpLine()
